import Head from 'next/head'
import Image from 'next/image'
import Featured from '../component/Featured'
import Hero from '../component/Hero'
import ProductCard from '../component/ProductCard'
import { ProductList } from '../component/ProductList'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome To Savage Denims</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <h1 className={styles.title}>
          
        </h1>

        <p className={styles.description}>
          <Featured />
          
        </p>

        <div className={styles.grid}>
          <ProductCard />
          
        </div>
      </main>

     
    </div>
  )
}
